"""gflvs LVS configuration for GF180MCU PDK."""

from gf180mcu.lvs.lvs import (
    DEFAULT_LVS_CONFIG,
    DEVICE_TEMPLATES,
    DRAWING_LAYERS,
    GDS_TABLE,
    INCLUDE_CAPACITORS,
    INCLUDE_DIODES,
    INCLUDE_FET,
    INCLUDE_GUARDRING,
    INCLUDE_RESISTORS,
    INCLUDE_VIA_CELLS,
    LABEL_LOGIC_LAYERS,
    LAYER_CONNECTIVITY,
    PIN_LOGIC_LAYERS,
    VIA_DRAWING_LAYERS,
    run_lvs_gf180mcu,
)

__all__ = [
    "DEFAULT_LVS_CONFIG",
    "DEVICE_TEMPLATES",
    "DRAWING_LAYERS",
    "GDS_TABLE",
    "INCLUDE_CAPACITORS",
    "INCLUDE_DIODES",
    "INCLUDE_FET",
    "INCLUDE_GUARDRING",
    "INCLUDE_RESISTORS",
    "INCLUDE_VIA_CELLS",
    "LABEL_LOGIC_LAYERS",
    "LAYER_CONNECTIVITY",
    "PIN_LOGIC_LAYERS",
    "VIA_DRAWING_LAYERS",
    "run_lvs_gf180mcu",
]
